# fly.toml file generated for ancient-breeze-2382 on 2023-04-10T12:12:33+10:00

app = "ancient-breeze-2382"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "syd"
processes = []

[build]
  # Use the heroku/python buildpack
  builder = "heroku/buildpacks:18"
  buildpacks = ["heroku/python"]



[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
